# Generated by Django 4.2.19 on 2025-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='lastname',
        ),
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
