# Generated by Django 4.2.19 on 2025-02-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_voter_firstname_remove_voter_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='registration',
        ),
    ]
