# Generated by Django 4.2.19 on 2025-02-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_candidate_bio_candidate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AddField(
            model_name='voter',
            name='selected_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.candidate'),
        ),
    ]
