# Generated by Django 4.2.19 on 2025-02-26 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_position_remove_candidate_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='selected_candidate',
        ),
        migrations.AddField(
            model_name='voter',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.candidate'),
        ),
    ]
