# Generated by Django 4.2.19 on 2025-02-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_voter_selected_candidate_voter_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='email',
        ),
    ]
