# Generated by Django 4.2.19 on 2025-02-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_voter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='candidate',
        ),
        migrations.AddField(
            model_name='position',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.candidate'),
        ),
        migrations.AddField(
            model_name='voter',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.position'),
        ),
    ]
