# Generated by Django 4.2.19 on 2025-02-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_remove_voter_candidate_position_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='candidates',
            field=models.ManyToManyField(related_name='positions', to='base.candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='base.voter')),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='votes',
            field=models.ManyToManyField(related_name='voters', to='base.vote'),
        ),
    ]
