# Generated by Django 4.2.19 on 2025-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_vote_candidate_alter_vote_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('registration_formats', models.TextField(help_text='Comma-separated registration number prefixes (e.g., CSC/,MAT/,AGR/)')),
            ],
        ),
    ]
