# Generated by Django 4.2.19 on 2025-03-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='base.school'),
        ),
        migrations.AddField(
            model_name='voter',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='base.school'),
        ),
    ]
