# Generated by Django 5.1.7 on 2025-03-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_candidate_school_voter_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_formats',
            field=models.TextField(),
        ),
    ]
