# Generated by Django 5.1.7 on 2025-03-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_school_registration_formats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='SchoolPosition',
        ),
    ]
